#include "dis86.h"

constexpr uint8_t DNE = 0xFF;

std::array<instr_fmt_t, 367> instr_tbl =
//     operation type      opcode1 opcode2   operand1          operand2          operand3           hidden
{
  {
    {  operation_e::ADD,       0x00,    DNE,   { operand_e::RM8,     operand_e::R8,      operand_e::None },    0x0 },
    {  operation_e::ADD,       0x01,    DNE,   { operand_e::RM16,    operand_e::R16,     operand_e::None },    0x0 },
    {  operation_e::ADD,       0x02,    DNE,   { operand_e::R8,      operand_e::RM8,     operand_e::None },    0x0 },
    {  operation_e::ADD,       0x03,    DNE,   { operand_e::R16,     operand_e::RM16,    operand_e::None },    0x0 },
    {  operation_e::ADD,       0x04,    DNE,   { operand_e::AL,      operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::ADD,       0x05,    DNE,   { operand_e::AX,      operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::PUSH,      0x06,    DNE,   { operand_e::ES,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::POP,       0x07,    DNE,   { operand_e::ES,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::OR,        0x08,    DNE,   { operand_e::RM8,     operand_e::R8,      operand_e::None },    0x0 },
    {  operation_e::OR,        0x09,    DNE,   { operand_e::RM16,    operand_e::R16,     operand_e::None },    0x0 },
    {  operation_e::OR,        0x0a,    DNE,   { operand_e::R8,      operand_e::RM8,     operand_e::None },    0x0 },
    {  operation_e::OR,        0x0b,    DNE,   { operand_e::R16,     operand_e::RM16,    operand_e::None },    0x0 },
    {  operation_e::OR,        0x0c,    DNE,   { operand_e::AL,      operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::OR,        0x0d,    DNE,   { operand_e::AX,      operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::PUSH,      0x0e,    DNE,   { operand_e::CS,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INVAL,     0x0f,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::ADC,       0x10,    DNE,   { operand_e::RM8,     operand_e::R8,      operand_e::None },    0x0 },
    {  operation_e::ADC,       0x11,    DNE,   { operand_e::RM16,    operand_e::R16,     operand_e::None },    0x0 },
    {  operation_e::ADC,       0x12,    DNE,   { operand_e::R8,      operand_e::RM8,     operand_e::None },    0x0 },
    {  operation_e::ADC,       0x13,    DNE,   { operand_e::R16,     operand_e::RM16,    operand_e::None },    0x0 },
    {  operation_e::ADC,       0x14,    DNE,   { operand_e::AL,      operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::ADC,       0x15,    DNE,   { operand_e::AX,      operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::PUSH,      0x16,    DNE,   { operand_e::SS,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::POP,       0x17,    DNE,   { operand_e::SS,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::SBB,       0x18,    DNE,   { operand_e::RM8,     operand_e::R8,      operand_e::None },    0x0 },
    {  operation_e::SBB,       0x19,    DNE,   { operand_e::RM16,    operand_e::R16,     operand_e::None },    0x0 },
    {  operation_e::SBB,       0x1a,    DNE,   { operand_e::R8,      operand_e::RM8,     operand_e::None },    0x0 },
    {  operation_e::SBB,       0x1b,    DNE,   { operand_e::R16,     operand_e::RM16,    operand_e::None },    0x0 },
    {  operation_e::SBB,       0x1c,    DNE,   { operand_e::AL,      operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::SBB,       0x1d,    DNE,   { operand_e::AX,      operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::PUSH,      0x1e,    DNE,   { operand_e::DS,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::POP,       0x1f,    DNE,   { operand_e::DS,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::AND,       0x20,    DNE,   { operand_e::RM8,     operand_e::R8,      operand_e::None },    0x0 },
    {  operation_e::AND,       0x21,    DNE,   { operand_e::RM16,    operand_e::R16,     operand_e::None },    0x0 },
    {  operation_e::AND,       0x22,    DNE,   { operand_e::R8,      operand_e::RM8,     operand_e::None },    0x0 },
    {  operation_e::AND,       0x23,    DNE,   { operand_e::R16,     operand_e::RM16,    operand_e::None },    0x0 },
    {  operation_e::AND,       0x24,    DNE,   { operand_e::AL,      operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::AND,       0x25,    DNE,   { operand_e::AX,      operand_e::IMM16,   operand_e::None },    0x0 },
    // SEGMENT OVERRIDE: ES
    {  operation_e::INVAL,     0x26,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::DAA,       0x27,    DNE,   { operand_e::AL,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::SUB,       0x28,    DNE,   { operand_e::RM8,     operand_e::R8,      operand_e::None },    0x0 },
    {  operation_e::SUB,       0x29,    DNE,   { operand_e::RM16,    operand_e::R16,     operand_e::None },    0x0 },
    {  operation_e::SUB,       0x2a,    DNE,   { operand_e::R8,      operand_e::RM8,     operand_e::None },    0x0 },
    {  operation_e::SUB,       0x2b,    DNE,   { operand_e::R16,     operand_e::RM16,    operand_e::None },    0x0 },
    {  operation_e::SUB,       0x2c,    DNE,   { operand_e::AL,      operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::SUB,       0x2d,    DNE,   { operand_e::AX,      operand_e::IMM16,   operand_e::None },    0x0 },
    // SEGMENT OVERRIDE: CS
    {  operation_e::INVAL,     0x2e,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::DAS,       0x2f,    DNE,   { operand_e::AL,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::XOR,       0x30,    DNE,   { operand_e::RM8,     operand_e::R8,      operand_e::None },    0x0 },
    {  operation_e::XOR,       0x31,    DNE,   { operand_e::RM16,    operand_e::R16,     operand_e::None },    0x0 },
    {  operation_e::XOR,       0x32,    DNE,   { operand_e::R8,      operand_e::RM8,     operand_e::None },    0x0 },
    {  operation_e::XOR,       0x33,    DNE,   { operand_e::R16,     operand_e::RM16,    operand_e::None },    0x0 },
    {  operation_e::XOR,       0x34,    DNE,   { operand_e::AL,      operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::XOR,       0x35,    DNE,   { operand_e::AX,      operand_e::IMM16,   operand_e::None },    0x0 },
    // SEGMENT OVERRIDE: SS
    {  operation_e::INVAL,     0x36,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::AAA,       0x37,    DNE,   { operand_e::AL,      operand_e::AH,      operand_e::None },    0x0 },
    {  operation_e::CMP,       0x38,    DNE,   { operand_e::RM8,     operand_e::R8,      operand_e::None },    0x0 },
    {  operation_e::CMP,       0x39,    DNE,   { operand_e::RM16,    operand_e::R16,     operand_e::None },    0x0 },
    {  operation_e::CMP,       0x3a,    DNE,   { operand_e::R8,      operand_e::RM8,     operand_e::None },    0x0 },
    {  operation_e::CMP,       0x3b,    DNE,   { operand_e::R16,     operand_e::RM16,    operand_e::None },    0x0 },
    {  operation_e::CMP,       0x3c,    DNE,   { operand_e::AL,      operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::CMP,       0x3d,    DNE,   { operand_e::AX,      operand_e::IMM16,   operand_e::None },    0x0 },
    // SEGMENT OVERRIDE: DS
    {  operation_e::INVAL,     0x3e,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::AAS,       0x3f,    DNE,   { operand_e::AL,      operand_e::AH,      operand_e::None },    0x0 },
    {  operation_e::INC,       0x40,    DNE,   { operand_e::AX,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INC,       0x41,    DNE,   { operand_e::CX,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INC,       0x42,    DNE,   { operand_e::DX,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INC,       0x43,    DNE,   { operand_e::BX,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INC,       0x44,    DNE,   { operand_e::SP,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INC,       0x45,    DNE,   { operand_e::BP,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INC,       0x46,    DNE,   { operand_e::SI,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INC,       0x47,    DNE,   { operand_e::DI,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::DEC,       0x48,    DNE,   { operand_e::AX,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::DEC,       0x49,    DNE,   { operand_e::CX,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::DEC,       0x4a,    DNE,   { operand_e::DX,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::DEC,       0x4b,    DNE,   { operand_e::BX,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::DEC,       0x4c,    DNE,   { operand_e::SP,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::DEC,       0x4d,    DNE,   { operand_e::BP,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::DEC,       0x4e,    DNE,   { operand_e::SI,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::DEC,       0x4f,    DNE,   { operand_e::DI,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::PUSH,      0x50,    DNE,   { operand_e::AX,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::PUSH,      0x51,    DNE,   { operand_e::CX,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::PUSH,      0x52,    DNE,   { operand_e::DX,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::PUSH,      0x53,    DNE,   { operand_e::BX,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::PUSH,      0x54,    DNE,   { operand_e::SP,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::PUSH,      0x55,    DNE,   { operand_e::BP,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::PUSH,      0x56,    DNE,   { operand_e::SI,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::PUSH,      0x57,    DNE,   { operand_e::DI,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::POP,       0x58,    DNE,   { operand_e::AX,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::POP,       0x59,    DNE,   { operand_e::CX,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::POP,       0x5a,    DNE,   { operand_e::DX,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::POP,       0x5b,    DNE,   { operand_e::BX,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::POP,       0x5c,    DNE,   { operand_e::SP,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::POP,       0x5d,    DNE,   { operand_e::BP,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::POP,       0x5e,    DNE,   { operand_e::SI,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::POP,       0x5f,    DNE,   { operand_e::DI,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::PUSHA,     0x60,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::POPA,      0x61,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INVAL,     0x62,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INVAL,     0x63,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INVAL,     0x64,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INVAL,     0x65,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INVAL,     0x66,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INVAL,     0x67,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::PUSH,      0x68,    DNE,   { operand_e::IMM16,   operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::IMUL,      0x69,    DNE,   { operand_e::R16,     operand_e::RM16,    operand_e::IMM16},   0x0 },
    {  operation_e::PUSH,      0x6a,    DNE,   { operand_e::IMM8,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::IMUL,      0x6b,    DNE,   { operand_e::R16,     operand_e::RM16,    operand_e::IMM8 },    0x0 },
    {  operation_e::INS,       0x6c,    DNE,   { operand_e::M8,      operand_e::DX,      operand_e::None },    0x0 },
    {  operation_e::INS,       0x6d,    DNE,   { operand_e::M16,     operand_e::DX,      operand_e::None },    0x0 },
    {  operation_e::OUTS,      0x6e,    DNE,   { operand_e::DX,      operand_e::M8,      operand_e::None },    0x0 },
    {  operation_e::OUTS,      0x6f,    DNE,   { operand_e::DX,      operand_e::M16,     operand_e::None },    0x0 },
    {  operation_e::JO,        0x70,    DNE,   { operand_e::REL8,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JNO,       0x71,    DNE,   { operand_e::REL8,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JB,        0x72,    DNE,   { operand_e::REL8,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JAE,       0x73,    DNE,   { operand_e::REL8,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JE,        0x74,    DNE,   { operand_e::REL8,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JNE,       0x75,    DNE,   { operand_e::REL8,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JBE,       0x76,    DNE,   { operand_e::REL8,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JA,        0x77,    DNE,   { operand_e::REL8,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JS,        0x78,    DNE,   { operand_e::REL8,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JNS,       0x79,    DNE,   { operand_e::REL8,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JP,        0x7a,    DNE,   { operand_e::REL8,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JNP,       0x7b,    DNE,   { operand_e::REL8,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JL,        0x7c,    DNE,   { operand_e::REL8,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JGE,       0x7d,    DNE,   { operand_e::REL8,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JLE,       0x7e,    DNE,   { operand_e::REL8,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JG,        0x7f,    DNE,   { operand_e::REL8,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::ADD,       0x80,      0,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::OR,        0x80,      1,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::ADC,       0x80,      2,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::SBB,       0x80,      3,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::AND,       0x80,      4,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::SUB,       0x80,      5,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::XOR,       0x80,      6,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::CMP,       0x80,      7,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::ADD,       0x81,      0,   { operand_e::RM16,    operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::OR,        0x81,      1,   { operand_e::RM16,    operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::ADC,       0x81,      2,   { operand_e::RM16,    operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::SBB,       0x81,      3,   { operand_e::RM16,    operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::AND,       0x81,      4,   { operand_e::RM16,    operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::SUB,       0x81,      5,   { operand_e::RM16,    operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::XOR,       0x81,      6,   { operand_e::RM16,    operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::CMP,       0x81,      7,   { operand_e::RM16,    operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::ADD,       0x82,      0,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::OR,        0x82,      1,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::ADC,       0x82,      2,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::SBB,       0x82,      3,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::AND,       0x82,      4,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::SUB,       0x82,      5,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::XOR,       0x82,      6,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::CMP,       0x82,      7,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::ADD,       0x83,      0,   { operand_e::RM16,    operand_e::IMM8_EXT,operand_e::None },    0x0 },
    {  operation_e::OR,        0x83,      1,   { operand_e::RM16,    operand_e::IMM8_EXT,operand_e::None },    0x0 },
    {  operation_e::ADC,       0x83,      2,   { operand_e::RM16,    operand_e::IMM8_EXT,operand_e::None },    0x0 },
    {  operation_e::SBB,       0x83,      3,   { operand_e::RM16,    operand_e::IMM8_EXT,operand_e::None },    0x0 },
    {  operation_e::AND,       0x83,      4,   { operand_e::RM16,    operand_e::IMM8_EXT,operand_e::None },    0x0 },
    {  operation_e::SUB,       0x83,      5,   { operand_e::RM16,    operand_e::IMM8_EXT,operand_e::None },    0x0 },
    {  operation_e::XOR,       0x83,      6,   { operand_e::RM16,    operand_e::IMM8_EXT,operand_e::None },    0x0 },
    {  operation_e::CMP,       0x83,      7,   { operand_e::RM16,    operand_e::IMM8_EXT,operand_e::None },    0x0 },
    {  operation_e::TEST,      0x84,    DNE,   { operand_e::RM8,     operand_e::R8,      operand_e::None },    0x0 },
    {  operation_e::TEST,      0x85,    DNE,   { operand_e::RM16,    operand_e::R16,     operand_e::None },    0x0 },
    {  operation_e::XCHG,      0x86,    DNE,   { operand_e::R8,      operand_e::RM8,     operand_e::None },    0x0 },
    {  operation_e::XCHG,      0x87,    DNE,   { operand_e::R16,     operand_e::RM16,    operand_e::None },    0x0 },
    {  operation_e::MOV,       0x88,    DNE,   { operand_e::RM8,     operand_e::R8,      operand_e::None },    0x0 },
    {  operation_e::MOV,       0x89,    DNE,   { operand_e::RM16,    operand_e::R16,     operand_e::None },    0x0 },
    {  operation_e::MOV,       0x8a,    DNE,   { operand_e::R8,      operand_e::RM8,     operand_e::None },    0x0 },
    {  operation_e::MOV,       0x8b,    DNE,   { operand_e::R16,     operand_e::RM16,    operand_e::None },    0x0 },
    {  operation_e::MOV,       0x8c,    DNE,   { operand_e::RM16,    operand_e::SREG,    operand_e::None },    0x0 },
    {  operation_e::LEA,       0x8d,    DNE,   { operand_e::R16,     operand_e::M16,     operand_e::None },    0x0 },
    {  operation_e::MOV,       0x8e,    DNE,   { operand_e::SREG,    operand_e::RM16,    operand_e::None },    0x0 },
    {  operation_e::POP,       0x8f,    DNE,   { operand_e::RM16,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::NOP,       0x90,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::XCHG,      0x91,    DNE,   { operand_e::CX,      operand_e::AX,      operand_e::None },    0x0 },
    {  operation_e::XCHG,      0x92,    DNE,   { operand_e::DX,      operand_e::AX,      operand_e::None },    0x0 },
    {  operation_e::XCHG,      0x93,    DNE,   { operand_e::BX,      operand_e::AX,      operand_e::None },    0x0 },
    {  operation_e::XCHG,      0x94,    DNE,   { operand_e::SP,      operand_e::AX,      operand_e::None },    0x0 },
    {  operation_e::XCHG,      0x95,    DNE,   { operand_e::BP,      operand_e::AX,      operand_e::None },    0x0 },
    {  operation_e::XCHG,      0x96,    DNE,   { operand_e::SI,      operand_e::AX,      operand_e::None },    0x0 },
    {  operation_e::XCHG,      0x97,    DNE,   { operand_e::DI,      operand_e::AX,      operand_e::None },    0x0 },
    {  operation_e::CBW,       0x98,    DNE,   { operand_e::AX,      operand_e::AL,      operand_e::None },    0x0 },
    {  operation_e::CWD,       0x99,    DNE,   { operand_e::DX,      operand_e::AX,      operand_e::None },    0x0 },
    {  operation_e::CALLF,     0x9a,    DNE,   { operand_e::FAR32,   operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INVAL,     0x9b,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::PUSHF,     0x9c,    DNE,   { operand_e::FLAGS,   operand_e::None,    operand_e::None },    0x1 },
    {  operation_e::POPF,      0x9d,    DNE,   { operand_e::FLAGS,   operand_e::None,    operand_e::None },    0x1 },
    {  operation_e::SAHF,      0x9e,    DNE,   { operand_e::AH,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::LAHF,      0x9f,    DNE,   { operand_e::AH,      operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::MOV,       0xa0,    DNE,   { operand_e::AL,      operand_e::MOFF8,   operand_e::None },    0x0 },
    {  operation_e::MOV,       0xa1,    DNE,   { operand_e::AX,      operand_e::MOFF16,  operand_e::None },    0x0 },
    {  operation_e::MOV,       0xa2,    DNE,   { operand_e::MOFF8,   operand_e::AL,      operand_e::None },    0x0 },
    {  operation_e::MOV,       0xa3,    DNE,   { operand_e::MOFF16,  operand_e::AX,      operand_e::None },    0x0 },
    {  operation_e::MOVS,      0xa4,    DNE,   { operand_e::DST8,    operand_e::SRC8,    operand_e::None },    0x0 },
    {  operation_e::MOVS,      0xa5,    DNE,   { operand_e::DST16,   operand_e::SRC16,   operand_e::None },    0x0 },
    {  operation_e::CMPS,      0xa6,    DNE,   { operand_e::DST8,    operand_e::SRC8,    operand_e::None },    0x0 },
    {  operation_e::CMPS,      0xa7,    DNE,   { operand_e::DST16,   operand_e::SRC16,   operand_e::None },    0x0 },
    {  operation_e::TEST,      0xa8,    DNE,   { operand_e::AL,      operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::TEST,      0xa9,    DNE,   { operand_e::AX,      operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::STOS,      0xaa,    DNE,   { operand_e::DST8,    operand_e::AL,      operand_e::None },    0x0 },
    {  operation_e::STOS,      0xab,    DNE,   { operand_e::DST16,   operand_e::AX,      operand_e::None },    0x0 },
    {  operation_e::LODS,      0xac,    DNE,   { operand_e::AL,      operand_e::SRC8,    operand_e::None },    0x0 },
    {  operation_e::LODS,      0xad,    DNE,   { operand_e::AX,      operand_e::SRC16,   operand_e::None },    0x0 },
    {  operation_e::SCAS,      0xae,    DNE,   { operand_e::AL,      operand_e::DST8,    operand_e::None },    0x0 },
    {  operation_e::SCAS,      0xaf,    DNE,   { operand_e::DST16,   operand_e::AX,      operand_e::None },    0x0 },
    {  operation_e::MOV,       0xb0,    DNE,   { operand_e::AL,      operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::MOV,       0xb1,    DNE,   { operand_e::CL,      operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::MOV,       0xb2,    DNE,   { operand_e::DL,      operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::MOV,       0xb3,    DNE,   { operand_e::BL,      operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::MOV,       0xb4,    DNE,   { operand_e::AH,      operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::MOV,       0xb5,    DNE,   { operand_e::CH,      operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::MOV,       0xb6,    DNE,   { operand_e::DH,      operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::MOV,       0xb7,    DNE,   { operand_e::BH,      operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::MOV,       0xb8,    DNE,   { operand_e::AX,      operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::MOV,       0xb9,    DNE,   { operand_e::CX,      operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::MOV,       0xba,    DNE,   { operand_e::DX,      operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::MOV,       0xbb,    DNE,   { operand_e::BX,      operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::MOV,       0xbc,    DNE,   { operand_e::SP,      operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::MOV,       0xbd,    DNE,   { operand_e::BP,      operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::MOV,       0xbe,    DNE,   { operand_e::SI,      operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::MOV,       0xbf,    DNE,   { operand_e::DI,      operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::ROL,       0xc0,      0,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::ROR,       0xc0,      1,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::RCL,       0xc0,      2,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::RCR,       0xc0,      3,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::SHL,       0xc0,      4,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::SHR,       0xc0,      5,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::SHL,       0xc0,      6,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::SAR,       0xc0,      7,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::ROL,       0xc1,      0,   { operand_e::RM16,    operand_e::IMM8_EXT,operand_e::None },    0x0 },
    {  operation_e::ROR,       0xc1,      1,   { operand_e::RM16,    operand_e::IMM8_EXT,operand_e::None },    0x0 },
    {  operation_e::RCL,       0xc1,      2,   { operand_e::RM16,    operand_e::IMM8_EXT,operand_e::None },    0x0 },
    {  operation_e::RCR,       0xc1,      3,   { operand_e::RM16,    operand_e::IMM8_EXT,operand_e::None },    0x0 },
    {  operation_e::SHL,       0xc1,      4,   { operand_e::RM16,    operand_e::IMM8_EXT,operand_e::None },    0x0 },
    {  operation_e::SHR,       0xc1,      5,   { operand_e::RM16,    operand_e::IMM8_EXT,operand_e::None },    0x0 },
    {  operation_e::SHL,       0xc1,      6,   { operand_e::RM16,    operand_e::IMM8_EXT,operand_e::None },    0x0 },
    {  operation_e::SAR,       0xc1,      7,   { operand_e::RM16,    operand_e::IMM8_EXT,operand_e::None },    0x0 },
    {  operation_e::RET,       0xc2,    DNE,   { operand_e::IMM16,   operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::RET,       0xc3,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::LES,       0xc4,    DNE,   { operand_e::ES,      operand_e::R16,     operand_e::M32  },    0x1 },
    {  operation_e::LDS,       0xc5,    DNE,   { operand_e::DS,      operand_e::R16,     operand_e::M32  },    0x1 },
    {  operation_e::MOV,       0xc6,      0,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::MOV,       0xc7,      0,   { operand_e::RM16,    operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::ENTER,     0xc8,    DNE,   { operand_e::BP,      operand_e::IMM16,   operand_e::IMM8 },    0x0 },
    {  operation_e::LEAVE,     0xc9,    DNE,   { operand_e::BP,      operand_e::SP,      operand_e::None },    0x3 },
    {  operation_e::RETF,      0xca,    DNE,   { operand_e::IMM16,   operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::RETF,      0xcb,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INT,       0xcc,    DNE,   { operand_e::LIT3,    operand_e::FLAGS,   operand_e::None },    0x2 },
    {  operation_e::INT,       0xcd,    DNE,   { operand_e::IMM8,    operand_e::FLAGS,   operand_e::None },    0x2 },
    {  operation_e::INTO,      0xce,    DNE,   { operand_e::FLAGS,   operand_e::None,    operand_e::None },    0x1 },
    {  operation_e::IRET,      0xcf,    DNE,   { operand_e::FLAGS,   operand_e::None,    operand_e::None },    0x1 },
    {  operation_e::ROL,       0xd0,      0,   { operand_e::RM8,     operand_e::LIT1,    operand_e::None },    0x0 },
    {  operation_e::ROR,       0xd0,      1,   { operand_e::RM8,     operand_e::LIT1,    operand_e::None },    0x0 },
    {  operation_e::RCL,       0xd0,      2,   { operand_e::RM8,     operand_e::LIT1,    operand_e::None },    0x0 },
    {  operation_e::RCR,       0xd0,      3,   { operand_e::RM8,     operand_e::LIT1,    operand_e::None },    0x0 },
    {  operation_e::SHL,       0xd0,      4,   { operand_e::RM8,     operand_e::LIT1,    operand_e::None },    0x0 },
    {  operation_e::SHR,       0xd0,      5,   { operand_e::RM8,     operand_e::LIT1,    operand_e::None },    0x0 },
    {  operation_e::SHL,       0xd0,      6,   { operand_e::RM8,     operand_e::LIT1,    operand_e::None },    0x0 },
    {  operation_e::SAR,       0xd0,      7,   { operand_e::RM8,     operand_e::LIT1,    operand_e::None },    0x0 },
    {  operation_e::ROL,       0xd1,      0,   { operand_e::RM16,    operand_e::LIT1,    operand_e::None },    0x0 },
    {  operation_e::ROR,       0xd1,      1,   { operand_e::RM16,    operand_e::LIT1,    operand_e::None },    0x0 },
    {  operation_e::RCL,       0xd1,      2,   { operand_e::RM16,    operand_e::LIT1,    operand_e::None },    0x0 },
    {  operation_e::RCR,       0xd1,      3,   { operand_e::RM16,    operand_e::LIT1,    operand_e::None },    0x0 },
    {  operation_e::SHL,       0xd1,      4,   { operand_e::RM16,    operand_e::LIT1,    operand_e::None },    0x0 },
    {  operation_e::SHR,       0xd1,      5,   { operand_e::RM16,    operand_e::LIT1,    operand_e::None },    0x0 },
    {  operation_e::SHL,       0xd1,      6,   { operand_e::RM16,    operand_e::LIT1,    operand_e::None },    0x0 },
    {  operation_e::SAR,       0xd1,      7,   { operand_e::RM16,    operand_e::LIT1,    operand_e::None },    0x0 },
    {  operation_e::ROL,       0xd2,      0,   { operand_e::RM8,     operand_e::CL,      operand_e::None },    0x0 },
    {  operation_e::ROR,       0xd2,      1,   { operand_e::RM8,     operand_e::CL,      operand_e::None },    0x0 },
    {  operation_e::RCL,       0xd2,      2,   { operand_e::RM8,     operand_e::CL,      operand_e::None },    0x0 },
    {  operation_e::RCR,       0xd2,      3,   { operand_e::RM8,     operand_e::CL,      operand_e::None },    0x0 },
    {  operation_e::SHL,       0xd2,      4,   { operand_e::RM8,     operand_e::CL,      operand_e::None },    0x0 },
    {  operation_e::SHR,       0xd2,      5,   { operand_e::RM8,     operand_e::CL,      operand_e::None },    0x0 },
    {  operation_e::SHL,       0xd2,      6,   { operand_e::RM8,     operand_e::CL,      operand_e::None },    0x0 },
    {  operation_e::SAR,       0xd2,      7,   { operand_e::RM8,     operand_e::CL,      operand_e::None },    0x0 },
    {  operation_e::ROL,       0xd3,      0,   { operand_e::RM16,    operand_e::CL,      operand_e::None },    0x0 },
    {  operation_e::ROR,       0xd3,      1,   { operand_e::RM16,    operand_e::CL,      operand_e::None },    0x0 },
    {  operation_e::RCL,       0xd3,      2,   { operand_e::RM16,    operand_e::CL,      operand_e::None },    0x0 },
    {  operation_e::RCR,       0xd3,      3,   { operand_e::RM16,    operand_e::CL,      operand_e::None },    0x0 },
    {  operation_e::SHL,       0xd3,      4,   { operand_e::RM16,    operand_e::CL,      operand_e::None },    0x0 },
    {  operation_e::SHR,       0xd3,      5,   { operand_e::RM16,    operand_e::CL,      operand_e::None },    0x0 },
    {  operation_e::SHL,       0xd3,      6,   { operand_e::RM16,    operand_e::CL,      operand_e::None },    0x0 },
    {  operation_e::SAR,       0xd3,      7,   { operand_e::RM16,    operand_e::CL,      operand_e::None },    0x0 },
    {  operation_e::INVAL,     0xd4,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INVAL,     0xd5,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INVAL,     0xd6,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::XLAT,      0xd7,    DNE,   { operand_e::AL,      operand_e::DS,      operand_e::BX   },    0x0 },
    {  operation_e::INVAL,     0xd8,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INVAL,     0xd9,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INVAL,     0xda,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INVAL,     0xdb,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INVAL,     0xdc,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INVAL,     0xdd,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INVAL,     0xde,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INVAL,     0xdf,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::LOOPNE,    0xe0,    DNE,   { operand_e::CX,      operand_e::REL8,    operand_e::None },    0x1 },
    {  operation_e::LOOPE,     0xe1,    DNE,   { operand_e::CX,      operand_e::REL8,    operand_e::None },    0x1 },
    {  operation_e::LOOP,      0xe2,    DNE,   { operand_e::CX,      operand_e::REL8,    operand_e::None },    0x1 },
    {  operation_e::JCXZ,      0xe3,    DNE,   { operand_e::CX,      operand_e::REL8,    operand_e::None },    0x1 },
    {  operation_e::IN,        0xe4,    DNE,   { operand_e::AL,      operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::IN,        0xe5,    DNE,   { operand_e::AX,      operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::OUT,       0xe6,    DNE,   { operand_e::IMM8,    operand_e::AL,      operand_e::None },    0x0 },
    {  operation_e::OUT,       0xe7,    DNE,   { operand_e::IMM8,    operand_e::AX,      operand_e::None },    0x0 },
    {  operation_e::CALL,      0xe8,    DNE,   { operand_e::REL16,   operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JMP,       0xe9,    DNE,   { operand_e::REL16,   operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JMPF,      0xea,    DNE,   { operand_e::FAR32,   operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JMP,       0xeb,    DNE,   { operand_e::REL8,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::IN,        0xec,    DNE,   { operand_e::AL,      operand_e::DX,      operand_e::None },    0x0 },
    {  operation_e::IN,        0xed,    DNE,   { operand_e::AX,      operand_e::DX,      operand_e::None },    0x0 },
    {  operation_e::OUT,       0xee,    DNE,   { operand_e::DX,      operand_e::AL,      operand_e::None },    0x0 },
    {  operation_e::OUT,       0xef,    DNE,   { operand_e::DX,      operand_e::AX,      operand_e::None },    0x0 },
    {  operation_e::INVAL,     0xf0,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INVAL,     0xf1,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    // REPNE: 0xf2, REPE: 0xf3
    {  operation_e::INVAL,     0xf2,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INVAL,     0xf3,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::HLT,       0xf4,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::CMC,       0xf5,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::TEST,      0xf6,      0,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::TEST,      0xf6,      1,   { operand_e::RM8,     operand_e::IMM8,    operand_e::None },    0x0 },
    {  operation_e::NOT,       0xf6,      2,   { operand_e::RM8,     operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::NEG,       0xf6,      3,   { operand_e::RM8,     operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::MUL,       0xf6,      4,   { operand_e::AX,      operand_e::AL,      operand_e::RM8  },    0x0 },
    {  operation_e::IMUL,      0xf6,      5,   { operand_e::AX,      operand_e::AL,      operand_e::RM8  },    0x0 },
    {  operation_e::DIV,       0xf6,      6,   { operand_e::AH,      operand_e::AL,      operand_e::RM8  },    0x0 },
    {  operation_e::DIV,       0xf6,      7,   { operand_e::AH,      operand_e::AL,      operand_e::RM8  },    0x0 },
    {  operation_e::TEST,      0xf7,      0,   { operand_e::RM16,    operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::TEST,      0xf7,      1,   { operand_e::RM16,    operand_e::IMM16,   operand_e::None },    0x0 },
    {  operation_e::NOT,       0xf7,      2,   { operand_e::RM16,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::NEG,       0xf7,      3,   { operand_e::RM16,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::MUL,       0xf7,      4,   { operand_e::DX,      operand_e::AX,      operand_e::RM16 },    0x0 },
    {  operation_e::IMUL,      0xf7,      5,   { operand_e::DX,      operand_e::AX,      operand_e::RM16 },    0x0 },
    {  operation_e::DIV,       0xf7,      6,   { operand_e::DX,      operand_e::AX,      operand_e::RM16 },    0x0 },
    {  operation_e::DIV,       0xf7,      7,   { operand_e::DX,      operand_e::AX,      operand_e::RM16 },    0x0 },
    {  operation_e::CLC,       0xf8,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::STC,       0xf9,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::CLI,       0xfa,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::STI,       0xfb,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::CLD,       0xfc,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::STD,       0xfd,    DNE,   { operand_e::None,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INC,       0xfe,      0,   { operand_e::RM8,     operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::DEC,       0xfe,      1,   { operand_e::RM8,     operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::INC,       0xff,      0,   { operand_e::RM16,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::DEC,       0xff,      1,   { operand_e::RM16,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::CALL,      0xff,      2,   { operand_e::RM16,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::CALLF,     0xff,      3,   { operand_e::M32,     operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JMP,       0xff,      4,   { operand_e::RM16,    operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::JMPF,      0xff,      5,   { operand_e::M32,     operand_e::None,    operand_e::None },    0x0 },
    {  operation_e::PUSH,      0xff,      6,   { operand_e::RM16,    operand_e::None,    operand_e::None },    0x0 },
  }
};


size_t dis86_instr_addr(dis86_instr_t *ins)
{
  return ins->addr;
}

size_t dis86_instr_n_bytes(dis86_instr_t *ins)
{
  return ins->n_bytes;
}

int instr_fmt_lookup(uint8_t opcode1, uint8_t opcode2, instr_fmt_t **_fmt)
{
  // TODO FIXME .. VERY INEFFICENT O(N) SEARCH
  // WE COULD DO A BINARY SEARCH, BUT REALLY WE SHOULD JUST USE A TABLE
  // THAT'S MUCH MORE EFFICENT FOR O(1) LOOKUPS. WE COULD EITHER BUILD
  // ANOTHER TABLE AT RUNTIME.. OR MORE IDEALLY, JUST REFORMT THE CURRENT
  // TABLE. THE PRIMARY CHALLENGE IS THE OPCODE2 THE WE OCCASIONALLY HAVE..
  // BUT NOT ALWAYS..

  int opcode1_found = 0;
  for (size_t i = 0; i < instr_tbl.size(); i++) {
    instr_fmt_t *fmt = &instr_tbl[i];
    if (opcode1 == fmt->opcode1) {
      if (fmt->op == operation_e::INVAL) return RESULT_NOT_FOUND;
      opcode1_found = 1;
      if (opcode2 == fmt->opcode2) {
        *_fmt = fmt;
        return RESULT_SUCCESS;
      }
    }
  }

  if (opcode1_found && opcode2 == DNE) {
    return RESULT_NEED_OPCODE2;
  }

  return RESULT_NOT_FOUND;
}

const std::array<const char* const, 93> instr_op_mneumonic =
{
    "aaa",    "aas",   "adc",    "add",
    "and",    "call",  "callf",  "cbw",
    "clc",    "cld",   "cli",    "cmc",
    "cmp",    "cmps",  "cwd",    "daa",
    "das",    "dec",   "div",    "enter",
    "hlt",    "imul",  "in",     "inc",
    "ins",    "int",   "into",   "inval",
    "iret",   "ja",    "jae",    "jb",
    "jbe",    "jcxz",  "je",     "jg",
    "jge",    "jl",    "jle",    "jmp",
    "jmpf",   "jne",   "jno",    "jnp",
    "jns",    "jo",    "jp",     "js",
    "lahf",   "lds",   "lea",    "leave",
    "les",    "lods",  "loop",   "loope",
    "loopne", "mov",   "movs",   "mul",
    "neg",    "nop",   "not",    "or",
    "out",    "outs",  "pop",    "popa",
    "popf",   "push",  "pusha",  "pushf",
    "rcl",    "rcr",   "ret",    "retf",
    "rol",    "ror",   "sahf",   "sar",
    "sbb",    "scas",  "shl",    "shr",
    "stc",    "std",   "sti",    "stos",
    "sub",    "test",  "xchg",   "xlat",
    "xor",
};

void dis86_instr_copy(dis86_instr_t *dst, dis86_instr_t *src)
{
  *dst = *src;
}
